#!/usr/bin/env python3
"""Import POC tenants from Umut Tenant Rapor Presales Excel export."""

import json
import sys
from datetime import datetime
from pathlib import Path

from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parents[1]
EXCEL = ROOT / "data" / "Umut Tenant Rapor Presales (5).xlsx"
OUT = ROOT / "src" / "data" / "tenants.json"
SEED = ROOT / "supabase" / "seed-poc-owners.sql"
DASHBOARD_YEAR = 2026
PERIOD_START = datetime(DASHBOARD_YEAR, 1, 1)
EXCLUDED_PARTNERS = {
    "nuevo.alo-tech.com",
    "teneo.alo-tech.com",
    "flowdesk.alo-tech.com",
    "lesacall.alo-tech.com",
}


def fmt_date(value):
    if value is None or value == "":
        return None
    if isinstance(value, datetime):
        return value.isoformat()
    return str(value)


def parse_active(value):
    if isinstance(value, str):
        v = value.strip().lower()
        if v in ("doğru", "dogru", "true", "yes", "1", "active"):
            return True
        if v in ("yanlış", "yanlis", "false", "no", "0", "inactive"):
            return False
    if value is not None:
        return bool(value)
    return None


def parse_created(value):
    if value is None or value == "":
        return None
    if isinstance(value, datetime):
        return value
    if isinstance(value, str):
        for fmt in ("%d.%m.%Y %I:%M %p", "%d.%m.%Y %H:%M", "%Y-%m-%d"):
            try:
                return datetime.strptime(value.strip(), fmt)
            except ValueError:
                continue
    return None


def in_period(dt):
    if dt is None:
        return False
    return dt.year == DASHBOARD_YEAR


def import_tenants(excel_path: Path) -> dict:
    wb = load_workbook(excel_path, read_only=True, data_only=True)
    rows = list(wb.active.iter_rows(values_only=True))
    wb.close()

    header_idx = next(
        i for i, row in enumerate(rows) if row and row[0] == "Account Name"
    )
    header = [str(col).strip() if col is not None else "" for col in rows[header_idx]]

    tenants = []
    for row in rows[header_idx + 1 :]:
        if not row or all(cell in (None, "") for cell in row):
            continue

        record = dict(zip(header, row))
        tenant_name = record.get("Tenant Name (Account Tenants)")
        if not tenant_name or str(tenant_name) in EXCLUDED_PARTNERS:
            continue

        created = parse_created(record.get("Created Time (Account Tenants)"))
        if not in_period(created):
            continue

        created_by = str(record.get("Created By (Account Tenants)") or "").strip()

        tenants.append(
            {
                "id": str(len(tenants) + 1),
                "tenantName": str(tenant_name),
                "accountName": str(record.get("Account Name") or "—"),
                "active": parse_active(record.get("Active")),
                "createdTime": fmt_date(created),
                "lastActivity": fmt_date(record.get("Last Activity Time (Account Tenants)")),
                "createdBy": created_by or "—",
                "pocOwner": created_by or None,
                "cluster": str(record.get("Telephony Cluster") or "—"),
            }
        )

    return {
        "tenants": tenants,
        "fetchedAt": datetime.now().isoformat(),
        "source": excel_path.name,
        "year": DASHBOARD_YEAR,
    }


def write_seed_sql(tenants: list) -> None:
    lines = [
        "-- POC owners from Excel Created By — auto-generated by import-excel.py",
        "-- Run in Supabase Dashboard → SQL Editor",
        "",
        "insert into poc_overrides (tenant_id, poc_owner, status) values",
    ]
    rows = []
    for t in tenants:
        owner = (t.get("pocOwner") or "").replace("'", "''")
        if not owner:
            continue
        rows.append(f"('{t['tenantName']}', '{owner}', 'active')")
    lines.append(",\n".join(rows))
    lines.append("on conflict (tenant_id) do update set poc_owner = excluded.poc_owner;")
    lines.append("")
    SEED.write_text("\n".join(lines), encoding="utf-8")


def main():
    excel_path = Path(sys.argv[1]) if len(sys.argv) > 1 else EXCEL
    if not excel_path.exists():
        print(f"Excel not found: {excel_path}", file=sys.stderr)
        sys.exit(1)

    payload = import_tenants(excel_path)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    write_seed_sql(payload["tenants"])

    active = sum(1 for t in payload["tenants"] if t["active"])
    print(f"Imported {len(payload['tenants'])} tenants ({DASHBOARD_YEAR}) from {excel_path.name}")
    print(f"  Active: {active}  Closed: {len(payload['tenants']) - active}")
    print(f"  Output: {OUT}")
    print(f"  Seed:   {SEED}")


if __name__ == "__main__":
    main()
